"""initial migration

Revision ID: 4f9aae97df85
Revises:
Create Date: 2025-11-15 13:00:58.412527

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "4f9aae97df85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("date_blacklisted", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("is_actively_blacklisted", sa.Boolean(), nullable=True),
        sa.Column("date_unblacklisted", sa.BigInteger(), nullable=True),
        sa.Column("why_unblacklisted", sa.String(), nullable=True),
        sa.CheckConstraint(
            "(is_actively_blacklisted = TRUE) OR (why_unblacklisted IS NOT NULL AND why_unblacklisted != '')",
            name="check_unblacklisted_reason",
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "custom_commands",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "logs",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("message_logs", sa.BigInteger(), nullable=True),
        sa.Column("member_logs", sa.BigInteger(), nullable=True),
        sa.Column("voice_logs", sa.BigInteger(), nullable=True),
        sa.Column("mod_logs", sa.BigInteger(), nullable=True),
        sa.Column("muterole", sa.BigInteger(), nullable=True),
        sa.Column("muterole_channel", sa.BigInteger(), nullable=True),
        sa.Column("reaction_logs", sa.BigInteger(), nullable=True),
        sa.Column("xp_mult", sa.Float(), nullable=True),
        sa.Column("levelup_channel", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("guild_id"),
        sa.UniqueConstraint("guild_id"),
    )
    op.create_table(
        "punishments",
        sa.Column("punishment_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("punishment", sa.String(), nullable=False),
        sa.Column("punishment_time", sa.BigInteger(), nullable=False),
        sa.Column("moderator_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("punishment_id"),
    )
    op.create_index("ix_guild_user_id", "punishments", ["guild_id", "user_id"], unique=False)
    op.create_table(
        "registrations",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("sexuality", sa.String(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("dms", sa.String(), nullable=True),
        sa.Column("relationship", sa.String(), nullable=True),
        sa.Column("mention", sa.Boolean(), nullable=True),
        sa.Column("dob", sa.String(), nullable=True),
        sa.Column("registered_at", sa.BigInteger(), nullable=True),
        sa.Column("age_verified", sa.Boolean(), nullable=True),
        sa.Column("artist_verified", sa.Boolean(), nullable=True),
        sa.Column("nsfw_lockout", sa.Boolean(), nullable=True),
        sa.Column("artist_lockout", sa.Boolean(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "levels",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("xp", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["logs.guild_id"],
        ),
        sa.PrimaryKeyConstraint("guild_id", "user_id"),
    )
    op.create_index("ix_guild", "levels", ["guild_id"], unique=False)
    op.create_index("ix_user_guild", "levels", ["user_id", "guild_id"], unique=False)
    op.create_table(
        "reg_roles",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("registered", sa.BigInteger(), nullable=True),
        sa.Column("mention_mention", sa.BigInteger(), nullable=True),
        sa.Column("mention_no_mention", sa.BigInteger(), nullable=True),
        sa.Column("dms_allowed", sa.BigInteger(), nullable=True),
        sa.Column("dms_not_allowed", sa.BigInteger(), nullable=True),
        sa.Column("dms_ask", sa.BigInteger(), nullable=True),
        sa.Column("gender_male", sa.BigInteger(), nullable=True),
        sa.Column("gender_female", sa.BigInteger(), nullable=True),
        sa.Column("gender_genderfluid", sa.BigInteger(), nullable=True),
        sa.Column("gender_agender", sa.BigInteger(), nullable=True),
        sa.Column("gender_non_binary", sa.BigInteger(), nullable=True),
        sa.Column("gender_transgender", sa.BigInteger(), nullable=True),
        sa.Column("gender_trans_male", sa.BigInteger(), nullable=True),
        sa.Column("gender_trans_female", sa.BigInteger(), nullable=True),
        sa.Column("relationship_taken", sa.BigInteger(), nullable=True),
        sa.Column("relationship_single", sa.BigInteger(), nullable=True),
        sa.Column("relationship_single_seeking", sa.BigInteger(), nullable=True),
        sa.Column("relationship_single_not", sa.BigInteger(), nullable=True),
        sa.Column("relationship_rather_not", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_asexual", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_bisexual", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_gay", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_lesbian", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_pansexual", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_aromantic", sa.BigInteger(), nullable=True),
        sa.Column("sexuality_rather_not", sa.BigInteger(), nullable=True),
        sa.Column("position_dominant", sa.BigInteger(), nullable=True),
        sa.Column("position_submissive", sa.BigInteger(), nullable=True),
        sa.Column("position_switch", sa.BigInteger(), nullable=True),
        sa.Column("position_rather_not", sa.BigInteger(), nullable=True),
        sa.Column("position_neither", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["logs.guild_id"],
        ),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reg_roles")
    op.drop_index("ix_user_guild", table_name="levels")
    op.drop_index("ix_guild", table_name="levels")
    op.drop_table("levels")
    op.drop_table("registrations")
    op.drop_index("ix_guild_user_id", table_name="punishments")
    op.drop_table("punishments")
    op.drop_table("logs")
    op.drop_table("custom_commands")
    op.drop_table("blacklisted_users")
    # ### end Alembic commands ###
